### ISSUE TITLE
Ex 3.2.4: Geometric Series mssing some words

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#12]
1.  Go to http://www.math.ubc.ca/~CLP/CLP2/clp_2_ic/subsection-41.html
2.  Expand the Example 3.2.4 Geometric series link.
3.  The 3rd sentence is not parseable (by me at least)

I see:

> Notice that we have chosen to start the summation index at n=0. That's fine. The first [2]
>
> N={0,1,2,⋯}
>
> while the notation

where [2] is footnote.  Expanding that footnote I see:

> Notice that we have chosen to start the summation index at n=0. That's fine. The first
> 
>    > It is actually quite common in computer science to think of 0
>    > as the first integer. In that context, the set of natural numbers is defined to contain 0:
>
> N={0,1,2,⋯}
>
> while the notation

I guess this is trying to say "The set of integers is denoted by" or maybe "the first few integers define the Sequence of natural numbers".  Honestly not sure.

**Comment by arechnitzer** [comment]
hmm - the html from pretext is wrong... but pdf from the pretext is fine. sigh.
