### ISSUE TITLE
Section 3.3: Convergence Test intro incorrectly states divergent series are useless

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#14]
> . Often you try to evaluate the sum approximately by truncating it, i.e. having the index run only up to some finite N, rather than infinity. But there is no point in doing so if the series diverges. 

The field of asymptotic analysis would disagree wiith you there!

Maybe I suggest:

> But there is often little point in doing so if the series diverges\footnote{The field of asymptotic analysis often makes use of the first few terms of divergent series to generate approximate solutions to problems; this, along with numerical computations, is one of the most important techniques in applied mathematics}

Although maybe those would more correctly be divergence sequences.  Having typed all this I'm loath to erase it but it doesn't follow quite a nicely as I thought when I started.

Run what I said past Michael Ward?

**Comment by cbm755** [comment]
I re-read this: I stand by my statement.  I.e., ignore thte self-doubt about "sequences": solutions via power series in $\epsilon$ is a Very Useful Thing.

**Comment by arechnitzer** [comment]
Suggested footnote =  (please comment / edit @cbm755  @joelfeldman )

The authors should be a little more careful making such a blanket statement. The field of asymptotic analysis often makes use of the first few terms of divergent series to generate approximate solutions to problems; this, along with numerical computations, is one of the most important techniques in applied mathematics. Indeed, there is a whole wonderful book devoted to playing with divergent series called, unsurprisingly, "Divergent Series" by G.H. Hardy. This is not to be confused with the "Divergent" series by V. Roth set in a post-apocalyptic dystopian Chicago. That latter series diverges quite dramatically from mathematical topics, while the former does not have a film adaptation.
</fn>

**Comment by cbm755** [comment]
"does not **YET** have a film adaptation."  Gotta encourage your readers to get on that...

**Comment by arechnitzer** [comment]
Updated accordingly.

**Comment by cbm755** [comment]
“Divergent series are the invention of the devil, and it is shameful to base on them any demonstration whatsoever.”  Abel.

Boyd, [The Devil’s Invention: Asymptotic, Superasymptotic and Hyperasymptotic Series](https://doi.org/10.1023%2FA%3A1006145903624)

Great intro paragraph  in that.
