### ISSUE TITLE
ex3.5.11 not defined at n=0

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#18]
$\sum_{n=0}^{\infty  \frac{x^n}{n^p}$.   There $n=0$ term is undefined here.

Should this whole example use $n=1$ as a starting value?

**Comment by cbm755** [comment]
See ex 3.5.19 which carefully discusses this.

**Comment by arechnitzer** [comment]
I've updated the example to start from n=1 and given a short footnote about avoiding 0^p.
