### ISSUE TITLE
Definition 1.1.8 isn't a mathematical definition

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#27]
I don't think this is a mathematical definition:

![image](https://user-images.githubusercontent.com/818622/211974296-95e3ad29-073a-47c0-8ea2-1a7ea0af1e65.png)

I understand that you want to attach words to the symbols before defining it (later in definition 1.1.19) .  Is there something else you could call this?  How about "Notation"?

I'm not (just) being pedantic.  The Chapter is called "1.1.4 The Definition of the Definite Integral", so if the first few words are Bold Definition its possible one will get confused.

**Comment by joelfeldman** [comment]
In the pdf version, this is Notation 1.1.8.  There is no "Notation" environment in pretext. I have added a sentence stating in words that the real definition of the definite integral comes later.
