### ISSUE TITLE
HTML page titles should include the "CLP2"

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#28]
This a very minor papercut, but see this screenshot:

![image](https://user-images.githubusercontent.com/818622/214634865-b81ffc6e-a0b1-42e6-8ddf-9226eddbbb89.png)

The titlebar there probably the html `<title>` or some such.  It says "Substitution".  I think it would be better if it said: "CLP2: Substitution" or "CLP2: 1.4 Substitution".

(I haven't checked what CLP1 and CLP3 do, but I imagine the same applies)

**Comment by joelfeldman** [comment]
I decided against this.
