### ISSUE TITLE
improving the FTC proof

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#29]
Screenshot from CLP-2 on FTC:

![image](https://user-images.githubusercontent.com/818622/215175411-8934bd10-df9d-4a84-ba08-298f5f150308.png)

- - - -

 "But since F'(x) = f(x)": this seems to put the cart before the horse.

They way I've always done this is by referencing the **Integral** Mean Value Theorem (not the regular MVT), which states that there exists some $c$ such that $\int_{x}^{x+h} f(t) dt = f(c) (x + h - x)$.  Then your argument about $c$ being squeezed works.

**Comment by cbm755** [comment]
To clarify (and since I've just learning that GitHub renders $\LaTeX$!): $F'(x) = \lim_{h \to 0} \frac{F(x + h) - F(x)}{h}$.  Then take $F(x) = \int_a^x f(t) \textrm{d} t$.  So $F'(x) = \lim_{h \to 0} \frac{\int_{x}^{x+h} f(t) \textrm{d} t}{h}$.  Invoking the IMVT as I indicate above, we have:
$$F'(x) = \lim_{h \to 0} \frac{f'(c)h}{h} = f'(c).$$

**Comment by joelfeldman** [comment]
The problem with this is that the IMVT has not been covered at this point. Furthermore the proof of the IMVT in CLP-2 uses the FTC. I have eliminated this footnote completely.
