### ISSUE TITLE
consider renaming "3.5.1 Definitions" to "3.5.1 radius and interval of convergence"

### ISSUE THREAD

**Issue by cbm755** [arechnitzer/CLP2#31]
Especially when working from the HTML version, it can be tricky to find where RofC and IofC are explained.  It took my quite a while digging around in Power Series and Taylor Series sections...  Eventually I switched to the PDF and grepped.

I think it might help to have those words appear in a section title.

**Comment by joelfeldman** [comment]
Implemented.
